services:
  user:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    container_name: user-dev
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run python -m user --host=127.0.0.1 --port=9051"
    depends_on:
      - db
    ports:
      - "9051:9051"
  db:
    image: postgres:16
    container_name: user-dev-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
