services:
  user_microservice_dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    container_name: user-dev
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run python -m user --host=0.0.0.0 --port=9051"
    depends_on:
      - db_user_microservice
    ports:  
      - "9051:9051"
  db_user_microservice:
    image: postgres:16
    container_name: user-dev-db
    volumes:
      - user_microservice_dev_postgres_data:/var/lib/user_microservice_dev_postgres_data/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  user_microservice_dev_postgres_data:
