name: Coverage
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: prepare environment
      run: |
        pip install poetry
        poetry install

    - name: Test with pytest
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report --fail-under=80